### ISSUE TITLE
[FEATURE]: Can txt read by obsidian as md, then support by other plugin?

### ISSUE THREAD

**Issue by atkdefender** [Falcion/UnitadeOBSIDIAN#24]
### What the essence of your feature request

I spend most of my time working hard to support my life. This leads me to record my voice and transcribe it into .txt files as notes. A .md file is too heavy for me. However, some plugins like Smart Connection do not support .txt files.

### On what OS you want to maintain your request.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
If I understood you correctly, you want to "render" .TXT just like .MD, it is not possible (at the moment), this topic was discussed in issue #4.

About enabling support for different plugins for .TXT extension: you must create issues in corresponsive plugins, because UNITADE as plugin can't "force" other plugins to work with custom extensions, but they in theory, create integration with UNITADE or just add support for .TXT files.
